In [2]:
import numpy as np
from numpy import linalg as LA
import scipy

In [9]:
A = np.array([[-1, 1, -1], [1, -1, -1], [-1, -1, -1]])
A

array([[-1,  1, -1],
       [ 1, -1, -1],
       [-1, -1, -1]])

In [10]:
B = np.array([[1, -3, 3/2], [1, 0, -3], [-1, -3, -3/2]])
B

array([[ 1. , -3. ,  1.5],
       [ 1. ,  0. , -3. ],
       [-1. , -3. , -1.5]])

In [11]:
eigenvalues, eigenvectors = LA.eig(A)

In [12]:
eigenvalues

array([ 1., -2., -2.])

In [ ]:
eigenvectors

array([[-0.57735027,  0.81649658,  0.42755853],
       [-0.57735027, -0.40824829,  0.38862863],
       [ 0.57735027,  0.40824829,  0.81618716]])

: 